services:

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: sandbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: ./worker
    container_name: execution-worker
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  gateway:
    build: ./gateway
    container_name: realtime-gateway
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://dev:dev@postgres:5432/sandbox
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      - redis
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start"

volumes:
  postgres_data:
