// Shared constants for message types and execution statuses
exports.MSG = {
    JOIN_ROOM: 'JOIN_ROOM',
    ROOM_JOINED: 'ROOM_JOINED',
    USER_JOINED: 'USER_JOINED',
    USER_LEFT: 'USER_LEFT',
    CODE_UPDATE: 'CODE_UPDATE',
    RUN_CODE: 'RUN_CODE',
    EXECUTION_QUEUED: 'EXECUTION_QUEUED',
    EXECUTION_STARTED: 'EXECUTION_STARTED',
    EXECUTION_OUTPUT: 'EXECUTION_OUTPUT',
    EXECUTION_FINISHED: 'EXECUTION_FINISHED',
    EXECUTION_ERROR: 'EXECUTION_ERROR',
    MESSAGE: 'MESSAGE'
};

exports.QUEUE = {
    EXECUTE: 'execute_jobs'
};
